{{- $globalSecrets := include "globalSecrets" . | fromYaml }}
{{- $globalApp := include "globalApp" . | fromYaml }}
{{- if $globalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-secret
  namespace: {{ $globalApp.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
type: {{ $globalSecrets.type | default "Opaque" }}
data:
  {{- range $key, $value := $globalSecrets.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }} 